version: '3.8'

services:
  apache:
    build:
      context: ./apache
      dockerfile: Dockerfile
    container_name: apache_server
    volumes:
      - ./apache/www:/usr/local/apache2/htdocs
      - ./apache/ssl:/usr/local/apache2/conf/ssl
      - ./apache/sites-enabled/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./apache/sites-enabled/httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
      - ./apache/logs:/usr/local/apache2/logs
    networks:
      - internal_net
      - external_net
    ports:
      - "80:80"
      - "443:443"
      - "5501:5501"
    restart: always

networks:
  internal_net:
    external: true
  external_net:
    external: true
