version: '3.8'

services:
  ftps:
    build:
      context: ./ftps
    ports:
      - "20:20"
      - "21:21"
      - "21100-21110:21100-21110"
    environment:
      - FTP_USER=user
      - FTP_PASS=pass
      - PASV_ADDRESS=127.0.0.1
      - PASV_MIN_PORT=21100
      - PASV_MAX_PORT=21110
    volumes:
      - ./ftps/config/vsftpd.conf:/etc/vsftpd/vsftpd.conf
      - ./ftps/home:/home/vsftpd
      - ./ftps/logs:/var/log/vsftpd
    networks:
      - internal_net

networks:
  internal_net:
    name: internal_net
    external: true
  external_net:
    name: external_net
    external: true
