services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/www/extranet:/usr/share/nginx/html/extranet
      - ./nginx/www/admin:/usr/share/nginx/html/admin
      - ./nginx/logs:/var/log/nginx
    networks:
      - internal_net
      - external_net

networks:
  internal_net:
    name: internal_net
    external: true
  external_net:
    name: external_net
    external: true
