services:
  apache:
    build:
      context: ./apache
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./apache/sites-enabled:/usr/local/apache2/conf/sites-enabled
      - ./apache/ssl:/usr/local/apache2/conf/ssl
      - ./apache/www/extranet:/usr/local/apache2/htdocs/extranet
      - ./apache/www/admin:/usr/local/apache2/htdocs/admin
      - ./apache/logs:/usr/local/apache2/logs
    networks:
      - internal_net
      - external_net

networks:
  internal_net:
    name: internal_net
    external: true
  external_net:
    name: external_net
    external: true
